/*
 * Aliyun Api Gateway Swagger Sample
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GeneratePictureVo struct {

	// 图片ID
	Id int64 `json:"id,omitempty"`

	// 图片名称
	Name string `json:"name,omitempty"`
}
