/*
 * Aliyun Api Gateway Swagger Sample
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AiGeneratePicQueryVo struct {

	// 异步任务ID
	TransactionId string `json:"transactionId,omitempty"`
}
