/*
 * Aliyun Api Gateway Swagger Sample
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GeneratePicturesVo struct {

	// 失败数量
	FailSize int64 `json:"failSize,omitempty"`

	// 图片列表
	List []GeneratePictureVo `json:"list,omitempty"`

	// 成功数量
	SuccessSize int32 `json:"successSize,omitempty"`

	// 请求总数
	TotalSize float32 `json:"totalSize,omitempty"`
}
